---
deployment:
  tasks:
    - export PATH=/opt/cpanel/ea-nodejs18/bin:$PATH
    - /opt/cpanel/ea-nodejs18/bin/npm ci --production=false
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - /opt/cpanel/ea-nodejs18/bin/pm2 restart tae-full-devsite --update-env
