/**
 * Design Templates
 * SPRINT 3: Curated templates including wedding invitations
 */

import { EditorObject } from '@/components/ProjectEditor/types';

export interface DesignTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  objects: EditorObject[];
  recommendedSize?: { width: number; height: number }; // in mm
}

export const DESIGN_TEMPLATES: DesignTemplate[] = [
  // Wedding Invitations
  {
    id: 'wedding-elegant',
    name: 'Elegant Wedding Invitation',
    category: 'wedding',
    description: 'Classic wedding invitation with ornate frame and script text',
    recommendedSize: { width: 127, height: 177.8 }, // 5x7 inches
    objects: [
      // Frame (ornate frame)
      {
        id: 'template-frame-1',
        type: 'border',
        x: 20,
        y: 20,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        width: 360,
        height: 340,
        borderDesignId: 'frame-wedding-1',
      },
      // Headline (script font)
      {
        id: 'template-headline-1',
        type: 'text',
        text: 'You Are Cordially Invited',
        x: 200,
        y: 80,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 32,
        fontFamily: 'Dancing Script',
        fontWeight: 700,
        fill: '#1f2937',
        textAlign: 'center',
      },
      // Names
      {
        id: 'template-names-1',
        type: 'text',
        text: 'Sarah & Michael',
        x: 200,
        y: 130,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 28,
        fontFamily: 'Playfair Display',
        fontWeight: 400,
        fill: '#1f2937',
        textAlign: 'center',
      },
      // Body text (serif)
      {
        id: 'template-body-1',
        type: 'text',
        text: 'Saturday, June 15th, 2024\nat 4:00 in the afternoon\n\nSt. Mary\'s Chapel\n123 Main Street\nSpringfield, IL',
        x: 200,
        y: 200,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 14,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 400,
        fill: '#4b5563',
        textAlign: 'center',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'wedding-modern',
    name: 'Modern Wedding Invitation',
    category: 'wedding',
    description: 'Clean modern design with geometric elements',
    recommendedSize: { width: 127, height: 177.8 },
    objects: [
      // Divider
      {
        id: 'template-divider-1',
        type: 'border',
        x: 50,
        y: 100,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        width: 300,
        height: 20,
        borderDesignId: 'divider-elegant',
      },
      // Headline
      {
        id: 'template-headline-2',
        type: 'text',
        text: 'Together With Our Families',
        x: 200,
        y: 60,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 18,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 300,
        fill: '#6b7280',
        textAlign: 'center',
      },
      // Names
      {
        id: 'template-names-2',
        type: 'text',
        text: 'Emma\n&\nJames',
        x: 200,
        y: 140,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 36,
        fontFamily: 'Playfair Display',
        fontWeight: 700,
        fill: '#1f2937',
        textAlign: 'center',
        lineHeight: 1.4,
      },
      // Body
      {
        id: 'template-body-2',
        type: 'text',
        text: 'Request the pleasure of your company\nat their wedding\n\nSeptember 20, 2024\nGrand Hotel\n456 Park Avenue',
        x: 200,
        y: 240,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 13,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 400,
        fill: '#4b5563',
        textAlign: 'center',
        lineHeight: 1.8,
      },
    ],
  },
  {
    id: 'wedding-vintage',
    name: 'Vintage Wedding Invitation',
    category: 'wedding',
    description: 'Vintage-style invitation with ornate corners and classic typography',
    recommendedSize: { width: 127, height: 177.8 },
    objects: [
      // Corner ornaments (top-left, top-right, bottom-left, bottom-right)
      {
        id: 'template-corner-tl',
        type: 'border',
        x: 15,
        y: 15,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        width: 50,
        height: 50,
        borderDesignId: 'corner-floral-1',
      },
      {
        id: 'template-corner-tr',
        type: 'border',
        x: 335,
        y: 15,
        scaleX: 1,
        scaleY: 1,
        rotation: 180,
        width: 50,
        height: 50,
        borderDesignId: 'corner-floral-1',
      },
      {
        id: 'template-corner-bl',
        type: 'border',
        x: 15,
        y: 335,
        scaleX: 1,
        scaleY: 1,
        rotation: -90,
        width: 50,
        height: 50,
        borderDesignId: 'corner-floral-1',
      },
      {
        id: 'template-corner-br',
        type: 'border',
        x: 335,
        y: 335,
        scaleX: 1,
        scaleY: 1,
        rotation: 90,
        width: 50,
        height: 50,
        borderDesignId: 'corner-floral-1',
      },
      // Headline
      {
        id: 'template-headline-3',
        type: 'text',
        text: 'Wedding Invitation',
        x: 200,
        y: 90,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 24,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 600,
        fill: '#78350f',
        textAlign: 'center',
      },
      // Names
      {
        id: 'template-names-3',
        type: 'text',
        text: 'Margaret & Robert',
        x: 200,
        y: 140,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 30,
        fontFamily: 'Dancing Script',
        fontWeight: 700,
        fill: '#1f2937',
        textAlign: 'center',
      },
      // Body
      {
        id: 'template-body-3',
        type: 'text',
        text: 'June 22nd, Two Thousand Twenty-Four\nat Half Past Four\n\nVictorian Gardens\n789 Heritage Lane\nCharleston, SC',
        x: 200,
        y: 210,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 13,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 400,
        fill: '#4b5563',
        textAlign: 'center',
        lineHeight: 1.7,
      },
    ],
  },
  
  // General Templates
  {
    id: 'birthday-classic',
    name: 'Classic Birthday Card',
    category: 'birthday',
    description: 'Simple birthday card with decorative elements',
    recommendedSize: { width: 127, height: 177.8 },
    objects: [
      {
        id: 'template-bday-1',
        type: 'text',
        text: 'Happy Birthday!',
        x: 200,
        y: 100,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 36,
        fontFamily: 'Playfair Display',
        fontWeight: 700,
        fill: '#dc2626',
        textAlign: 'center',
      },
      {
        id: 'template-bday-2',
        type: 'label-shape',
        labelShapeType: 'pill',
        text: 'Celebrate!',
        x: 200,
        y: 180,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        width: 150,
        height: 50,
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 600,
        fill: '#ffffff',
        backgroundColor: '#dc2626',
        cornerRadius: 25,
      },
    ],
  },
  {
    id: 'thank-you-elegant',
    name: 'Elegant Thank You',
    category: 'thank-you',
    description: 'Formal thank you card',
    recommendedSize: { width: 101.6, height: 152.4 }, // 4x6
    objects: [
      {
        id: 'template-thanks-1',
        type: 'text',
        text: 'Thank You',
        x: 200,
        y: 80,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 32,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 600,
        fill: '#1f2937',
        textAlign: 'center',
      },
      {
        id: 'template-thanks-2',
        type: 'text',
        text: 'For Your Kindness',
        x: 200,
        y: 130,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 16,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 400,
        fill: '#4b5563',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'announcement-birth',
    name: 'Birth Announcement',
    category: 'announcement',
    description: 'Birth announcement template',
    recommendedSize: { width: 127, height: 177.8 },
    objects: [
      {
        id: 'template-birth-1',
        type: 'text',
        text: 'We\'re Having a Baby!',
        x: 200,
        y: 80,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 28,
        fontFamily: 'Playfair Display',
        fontWeight: 700,
        fill: '#1f2937',
        textAlign: 'center',
      },
      {
        id: 'template-birth-2',
        type: 'text',
        text: 'Due: March 2024',
        x: 200,
        y: 140,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 18,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 400,
        fill: '#4b5563',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'holiday-christmas',
    name: 'Christmas Card',
    category: 'holiday',
    description: 'Holiday greeting card',
    recommendedSize: { width: 127, height: 177.8 },
    objects: [
      {
        id: 'template-xmas-1',
        type: 'text',
        text: 'Merry Christmas',
        x: 200,
        y: 100,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 32,
        fontFamily: 'Playfair Display',
        fontWeight: 700,
        fill: '#dc2626',
        textAlign: 'center',
      },
      {
        id: 'template-xmas-2',
        type: 'text',
        text: '& Happy New Year',
        x: 200,
        y: 150,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 24,
        fontFamily: 'Playfair Display',
        fontWeight: 400,
        fill: '#065f46',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'graduation-classic',
    name: 'Graduation Card',
    category: 'graduation',
    description: 'Congratulations graduation card',
    recommendedSize: { width: 127, height: 177.8 },
    objects: [
      {
        id: 'template-grad-1',
        type: 'text',
        text: 'Congratulations',
        x: 200,
        y: 90,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 30,
        fontFamily: 'Playfair Display',
        fontWeight: 700,
        fill: '#1f2937',
        textAlign: 'center',
      },
      {
        id: 'template-grad-2',
        type: 'text',
        text: 'On Your Graduation',
        x: 200,
        y: 140,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 20,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 400,
        fill: '#4b5563',
        textAlign: 'center',
      },
      {
        id: 'template-grad-3',
        type: 'label-shape',
        labelShapeType: 'badge-circle',
        text: '2024',
        x: 200,
        y: 220,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        width: 100,
        height: 100,
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 700,
        fill: '#1f2937',
        backgroundColor: '#fef3c7',
        cornerRadius: 50,
      },
    ],
  },
  {
    id: 'sympathy-elegant',
    name: 'Sympathy Card',
    category: 'sympathy',
    description: 'Sympathy card template',
    recommendedSize: { width: 127, height: 177.8 },
    objects: [
      {
        id: 'template-sym-1',
        type: 'text',
        text: 'With Sympathy',
        x: 200,
        y: 100,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 26,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 600,
        fill: '#1f2937',
        textAlign: 'center',
      },
      {
        id: 'template-sym-2',
        type: 'text',
        text: 'Our thoughts are with you\nin this time of sorrow',
        x: 200,
        y: 160,
        scaleX: 1,
        scaleY: 1,
        rotation: 0,
        fontSize: 14,
        fontFamily: 'Cormorant Garamond',
        fontWeight: 400,
        fill: '#4b5563',
        textAlign: 'center',
        lineHeight: 1.8,
      },
    ],
  },
];

/**
 * Get templates by category
 */
export function getTemplatesByCategory(category: string): DesignTemplate[] {
  return DESIGN_TEMPLATES.filter(t => t.category === category);
}

/**
 * Get template by ID
 */
export function getTemplateById(id: string): DesignTemplate | undefined {
  return DESIGN_TEMPLATES.find(t => t.id === id);
}
